# Generated by Django 2.1 on 2021-01-13 23:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('enamil', models.EmailField(max_length=100, verbose_name='Email')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=300, verbose_name='Teléfono')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='About', verbose_name='Adjunta la Imagen del About')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de',
            },
        ),
    ]
