# Generated by Django 2.1 on 2021-01-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210113_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=100, verbose_name='Tiempo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('actividades', models.CharField(max_length=300, verbose_name='Actividades')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
    ]
