# Generated by Django 2.1 on 2021-01-14 03:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employement',
            name='actividades',
            field=ckeditor.fields.RichTextField(verbose_name='Actividades'),
        ),
    ]
