# Generated by Django 2.1 on 2021-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso_education_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id de Certificacion'),
        ),
    ]
