# Generated by Django 2.1 on 2021-01-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='firma',
        ),
        migrations.AlterField(
            model_name='reference',
            name='testimonio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Testimonio'),
        ),
    ]
