# Generated by Django 2.1 on 2021-01-15 01:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210114_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='testimonio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Testimonio'),
        ),
    ]
