# Generated by Django 2.1 on 2021-01-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210114_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='testimonio',
        ),
        migrations.AlterField(
            model_name='reference',
            name='referencia',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
    ]
