# Generated by Django 2.1 on 2021-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210114_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='media/About', verbose_name='Adjunta la Imagen del About'),
        ),
    ]
