# Generated by Django 2.1 on 2021-01-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210119_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Linkedin'),
        ),
    ]
