# Generated by Django 2.1 on 2021-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_about_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about', verbose_name='Adjunta la Imagen del About'),
        ),
    ]
